# Generated by Django 5.2.9 on 2026-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_predictions',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
