# Generated by Django 5.2 on 2026-01-02 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('reporter_cin', models.CharField(max_length=20)),
                ('accident_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('car_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('other_name', models.CharField(max_length=100)),
                ('other_cin', models.CharField(max_length=20)),
                ('other_phone', models.CharField(max_length=20)),
                ('guilty', models.CharField(choices=[('me', 'Me'), ('other', 'Other Party'), ('both', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('cancellations', models.ManyToManyField(blank=True, related_name='canceled_accidents', to=settings.AUTH_USER_MODEL)),
                ('confirmations', models.ManyToManyField(blank=True, related_name='confirmed_accidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('reporter_cin', models.CharField(max_length=20)),
                ('accident_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('localisation', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('car_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('other_name', models.CharField(max_length=100)),
                ('other_cin', models.CharField(max_length=20)),
                ('other_phone', models.CharField(max_length=20)),
                ('guilty', models.CharField(choices=[('me', 'Me'), ('other', 'Other Party'), ('both', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
